# Generated by Django 5.1.7 on 2025-03-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="products",
            field=models.ManyToManyField(related_name="Categories", to="core.product"),
        ),
    ]
